[development]
databases.sqlite = { url = "dev.db" }

# NOTE: Do NOT !!! !!! use these keys; instead generate random keys
# for example with
# dd if=/dev/urandom bs=32 count=1 | base64
# and copy and paste here. Must be 32 bytes, base64 encoded.

[staging]
secret_key = "PWeJtRywvgstfLa0DPdhI/zR7nGI8gT+6otIEmH+5v0="
databases.sqlite = { url = "stage.db" }

[production]
address = "0.0.0.0"
port = 8080
secret_key = "PWeJtRywvgstfLa0DPdhI/zR7nGI8gT+6otIEmH+5v0="
databases.sqlite = { url = "prod.db" }

# Set this to use a subdomain or other base URL
# base_url = "https://nora.codes/quotes/"

